### ISSUE TITLE
Any demo on C-index and feature importance?

### ISSUE THREAD

**Issue by JingyiShi** [IyarLin/survXgboost#11]
Hi! First, thank you for writing the survXgboost package. I'm new to using XGBoost on survival analysis and found your package and demo very helpful.
Now my question is: How can I continue to get C-index and feature importance using your package after I get a XGBoost-Cox model? Do you have any demo on it? Thanks much!

**Comment by IyarLin** [comment]
Hi, thanks for you feedback.
To estimate the c-index you need risk scores. In the package README there's an illustration of how to do that.

As for feature importance: The resulting object from the `xgb.train.surv` function is of class `xgb.Booster` which means you can apply to it all methods that apply to that class. In particular you can use the `xgb.importance` function (see more [here](https://xgboost.readthedocs.io/en/stable/R-package/xgboostPresentation.html#view-feature-importance-influence-from-the-learnt-model))
