### ISSUE TITLE
"doesn't handle missing values at the moment"

### ISSUE THREAD

**Issue by rexdouglass** [IyarLin/survXgboost#2]
Does the package still no longer handle missing values and if so what exactly about it breaks?

There is this line in the example which if I comment out still runs without warning or error
"lung <- lung[complete.cases(lung), ] # doesn't handle missing values at the moment"

**Comment by IyarLin** [comment]
Hi,

That's actually a good question: the code does seem to run smoothly. Can't remember what it was that failed when I built it. I'll remove that comment. Let me know if you run into something.
