### ISSUE TITLE
how to get feature importance?

### ISSUE THREAD

**Issue by KKAres** [IyarLin/survXgboost#4]
Hello, recently I used your package for survival analysis, but there are two problems that have not been solved. The first one is how to output the best parameter combination; The second is how to output the feature importance of the best model. Looking forward to your answers

**Comment by IyarLin** [comment]
Hi,

I've changed the resulting object class such that it could be used with all methods that apply to the "xgb.Booster" class. Please consult the xgboost library documentation accordignly.
