### ISSUE TITLE
It seemd that 'const' not  defined or assigned

### ISSUE THREAD

**Issue by Boya818** [IyarLin/survXgboost#6]
![MicrosoftTeams-image (24)](https://github.com/IyarLin/survXgboost/assets/121234493/ddb0ef27-dff9-483d-b1ea-5f3c847e70f6)
![MicrosoftTeams-image (23)](https://github.com/IyarLin/survXgboost/assets/121234493/a3c356f0-9a2b-4b99-9abc-90555c01810a)

**Comment by IyarLin** [comment]
The error you are getting relates to a function named `Hist`, not the const object.
Make sure you have the library `prodlim` installed.
