### ISSUE TITLE
Use the Breslow estimate instead of Kalbfleisch-Prentice estimate

### ISSUE THREAD

**Issue by erikvona** [IyarLin/survXgboost#7]
This package uses `survival::basehaz` from a Cox model without parameters to calculate the baseline hazard.

Per the documentation, that is a derivative of the `survfit.coxph` function, which uses the Kalbfleisch-Prentice estimate.

However, for XGBoost, the appropriate baseline hazard to use is the Breslow estimate. The Breslow estimate also does not need scaling, it's scaled appropriately for the model. It can be obtained by using `survfit` with stype = 2.

**Comment by IyarLin** [comment]
Hi, this project isn't actively maintained at the moment. Would like to open a pull request with your suggested improvement?

**Comment by erikvona** [comment]
I've already done so, it's #8 , but one moment, I've found some anomalies while testing with the most recent build of xgboost

**Comment by IyarLin** [comment]
Merged your PR. Much appreciated. Thanks.
