### ISSUE TITLE
Some additional fixes

### ISSUE THREAD

**Issue by erikvona** [IyarLin/survXgboost#9]
Hi Ilyar,

Sorry for the second message, I had noticed some oddities and have made some more substantial changes.
Primarily, the survival estimates were only calibrated if mean(linear predictor) was 0 (so geomean HR = 1), but that's not always the case.

I've stored the mean linear predictor with the model, and modified the predict function to adjust for the mean linear predictor.
In this process, I also noted the predict function could not predict for a single timepoint, so I fixed that.

I've added an additional example to the readme as well so people can easily see this package produces well calibrated survival estimates.

Attaching a pull request.

**Comment by IyarLin** [comment]
Look sgood. Merging.
